#!/usr/bin/env python

import rospy
from std_msgs.msg import Float64
from std_srvs.srv import Trigger, TriggerResponse


class ThrowerBase:
    def __init__(self):
        self._pos_reload = 0.134
        self._pos_throw = -1.40
        self._cmd_pub = rospy.Publisher('thrower_position_controller/command', Float64, queue_size=1)
        rospy.Service('throw', Trigger, self.throw_callback)
        rospy.Service('reload', Trigger, self.reload_callback)
        rospy.spin()


    def throw_callback(self, request):
        cmd_msg = Float64()
        cmd_msg.data = self._pos_throw
        self._cmd_pub.publish(cmd_msg)
        response = TriggerResponse()
        response.message = 'Throwing robot!'
        response.success = True
        return response

    
    def reload_callback(self, request):
        cmd_msg = Float64()
        cmd_msg.data = self._pos_reload
        self._cmd_pub.publish(cmd_msg)
        response = TriggerResponse()
        response.message = "Reloading"
        response.success = True
        return response


def main():
    rospy.init_node('thrower_base')
    thrower_base = ThrowerBase()


if __name__ == '__main__':
    main()
